[project]
name = "trainable-entity-extractor"
version = "0.16"
description = "This tool is a trainable text/PDF to entity extractor"
url = "https://github.com/huridocs/trainable-entity-extractor"
license = { file = "LICENSE" }
authors = [{ name = "HURIDOCS"}]

[project.dependencies]
requires = { python = ">=3.11" }
dependencies = { path = "requirements.txt" }

[build-system]
requires = ["setuptools>=75.3.0"]  # Minimum setuptools version required by PEP 518

[tool.setuptools]
package_dir = "src"